version: "3.8"
services:

  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - frontend

  web:
    build: .
    ports:
      - "8000:8000"
    networks:
      - frontend

  worker:
    build: .
    networks:
      - frontend

networks:
  frontend:
